# project:
#   type: website

# website:
#   page-footer: "Copyright 2022, Fraunhofer IEE."
#   back-to-top-navigation: true
#   page-navigation: true
#   title: Powfacpy

#   navbar:
#     background: primary
#     search: true
#     left:
#       - text: "Home"
#         href: docs/home/
#       - text: "Tutorials"
#         href: docs/tutorials
#       - text: "API"
#         href: docs/api/
#       - text: "How-to-contribute"
#     right:
#       - icon: github
#         href: https://github.com/FraunhIEE-UniKassel-PowSysStability/powfacpy
#       - icon: mail
#         href: simon.eberlein@iee.fraunhofer.de

#   sidebar:
#     - title: "Introduction"
#       style: floating
#       background: light
#       align: left
#       contents:
#         - home/index.qmd

#     - title: "Tutorials"
#       contents:
#         - tutorials/tutorials.qmd
#         - tutorials/getting_started.qmd
#         - tutorials/simulation_and_plotting.qmd
#         - tutorials/study_cases.qmd

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true

# metadata-files: 
#   - api/_sidebar.yml

# quartodoc:
#   style: pkgdown
#   parser: sphinx
#   dir: api
#   package: powfacpy
#   source_dir: ./src
#   render_interlinks: true
#   sidebar: "api/_sidebar.yml"
#   sections:
#     - title: Modules
#       desc: |
#         Below are the Modules of the Powfacpy.
#       contents:
#         - active_project_interface
#         - database_interface
#         - plot_interface
#         - dyn_sim_interface
#         - case_studies
#         - results_interface



project:
  type: website

website:
  page-footer: "Copyright 2022, Fraunhofer IEE."
  back-to-top-navigation: true
  page-navigation: true
  title: Powfacpy
  navbar:
    pinned: true
    background: primary
    search: true
    left:
      - file: docs/home/index.qmd
        text: Home
      - file: docs/tutorials/tutorials.qmd
        text: Tutorials
      - file: docs/build/powfacpy/index.html
        text: API
      - href: docs/Contribution/contribution.qmd
        text: How-To-Contribute
    right:
      - icon: github
        href: https://github.com/FraunhIEE-UniKassel-PowSysStability/powfacpy
      - icon: mail
        href: simon.eberlein@iee.fraunhofer.de

  sidebar:
    - title: "Introduction"
      style: floating
      background: light
      align: left
      contents:
        - docs/home/index.qmd

    - title: "Tutorials"
      contents:
        - docs/tutorials/tutorials.qmd
        - docs/tutorials/getting_started.qmd
        - docs/tutorials/simulation_and_plotting.qmd
        - docs/tutorials/study_cases.qmd

    - title: "How-To-Contribute"
      contents:
        - docs/Contribution/contribution.qmd
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
resources: 
  - docs/build/powfacpy/**