project:
  type: website
execute: 
  freeze: auto

website:
  title: "Fraunhoferquartowebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Fraunhofer

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



