---
title: "Tutorials "
format:
  html:
    code-fold: true
jupter: python3
---

[Home](index.qmd) /**Tutorials**

The tutorials are Jupyter notebooks which you can find in the Tutorials section.

You can use the PowerFactory project 'powfacpy_tests' from `here <https://github.com/FraunhIEE-UniKassel-PowSysStability/powfacpy/tree/main/powerfactory_projects>`_ 
to run the commands in the tutorials locally. 

## Getting started

Start here with the **Getting started with Powfacpy section** .
This tutorial gives an overview of the interaction with the *PowerFactory* 
database using *powfacpy*. The methods introduced in this tutorial serve as a basis to 
do more complex things and to write more readable code using less lines of code.

## Dynamic Simulation and Plotting

The  **Dynamic Simulation and Plotting section** shows how to conveniently 
simulate and plot with a syntax similar to matplotlib. It is also depicted how to export data to csv format
and use external plotting libraries such as matplotlib. 

## Study Cases

The **Study Case section**
provides a flexible method to automatically create study cases from different data.