on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Configure Git
        run: |
          git config --global user.email "quarto-github-actions@example.com"
          git config --global user.name "Quarto GitHub Actions"

      - name: Render and Publish
        run: |
          cd quartowebsite
          quartodoc build
          quarto render
          quarto publish gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has write access